image: node:latest

stages:
  - deploy

services:
  - mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: hello_world_test
  MYSQL_ROOT_PASSWORD: mysql

connect:
  image: mysql
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

deploy:heroku:
  type: deploy
  stage: production
  when: manual
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_MASTER --api-key=$HEROKU_API_KEY
  only:
    - master

